services:
  - type: web
    name: codecommunity-backend
    env: node
    plan: free
    region: oregon
    buildCommand: "yarn install && yarn run rebuild-mongoose"
    startCommand: "yarn start"
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
